name: ci checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:


  check_doc_strings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run Interrogate locally
        run: |
          if [ $(interrogate -c pyproject.toml -v . -f 100 | grep "FAILED" | wc -l) = 1 ]; then
             echo "necessary docstrings missing:"
             interrogate -vv . -f 100 
             exit 1
          fi



  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable




